[package]
name = "test-b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
member-a = { path = "../test-repo-a/member-a" }
member-b = { path = "../test-repo-a/member-b" }